# Use the latest Ubuntu LTS as the base image
FROM ubuntu:20.04

# Set the DEBIAN_FRONTEND to noninteractive to suppress prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Define an argument for the tag name
ARG TAG_NAME=membership

# Update the image and install system packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget \
    xvfb \
    zip \
    ca-certificates \
    libnss3-dev \
    libasound2 \
    libxss1 \
    libappindicator3-1 \
    libindicator7 \
    gconf-service \
    libgconf-2-4 \
    libpango1.0-0 \
    xdg-utils \
    fonts-liberation \
    wmctrl

# Install Robot Framework and SeleniumLibrary along with other required Python packages
RUN pip3 install selenium==4.15.2 \
                 robotframework==6.1.1 \
                 robotframework-seleniumlibrary==6.2.0 \
                 robotframework-retryfailed==0.2.0 \
                 robotframework-pabot==2.16.0 \
                 openpyxl==3.1.2 \
                 allure-robotframework==2.13.2 \
                 webdrivermanager \
                 pandas

# Use a base image with Python
FROM python:3.9-slim

# Set working directory
WORKDIR /robot

# Install Robot Framework and required libraries
RUN pip install robotframework

# Copy the test files based on TAG_NAME
COPY . /robot

# Set the environment variable for the tag name
ENV Tags=membership

# Set the default command to run Robot Framework with an option to specify tags
CMD ["robot", "--i", "$[Tags]", "/robot/Web/RR/TestCases/"]
